apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: dev
#  $(cat dev.csr | base64 | tr -d '\n')
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RaR1YyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdUpVRjB5bHNidmxzdnRiZFZvSnRiYVo2THg5eUJXVVk3Ykc2enhVU08xcjR4d0trCnRtUE1BdEhYVFJWMnphdUprTHNuckFheFh0NUJSTnVBOFFHQ2FJVjVadTlMNzg1NGY3cmU3VlZQWnlYSnIwVCsKbUdndlFpSHhTL1lFbGdmSTBXejVlWnJiY2xPd21vWkxnVnVvR20yTFZpMFdDRzN5K0M2UHdzekJzOEJLRXF1bgpnc3RiN2pBYndubkFRRkRQOGtYZkcvZERjanVzZmdIRGRtTzQ1eHd3R0ZHOVdLVG05U1FiVEl1QkdVZ1AySTFWCmNBc0EyenBkWC9DUHozdklxMFN1alBWUWNpSVlaZ1J6L2lyS2VwcEJHbWVLaEN0MUpzQ3FXR1o5cExWVmhPUVQKMHI1ckFJRUtma2RreitwUkxnYkNwdU9HSnEzakxkK2N0cVRVMHdJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFIY1ZTWk0yYW96Z2JYN1FlcGIwSkpFcEVYaDVZYW5wMlpnbnJ4aENHeE1LdkN2UEdsZWVQWi83CmhSTTBPRExyclYraFdCdk10enF3STZSUFdKR1BYY29taHhjeUdCTU9UbC9ySmdHbFYxL3ByNHBKbG9lTUUrZjYKdmY0MGhPUVZ3WEtabytPa1orMEJ2R3N2UUxLdEIyTUlVTGFDb2hVc09NamlUc3lVTUloUnBBYVpTM3RSbkFmSApDSnY3R3d1TERzV1FvQ2xnaVpRcFdab3lBak83SXdNUkYxVTZ6UmdtTFk1TlZuNzc1KzA3MnNOZHRxaEd3bWtOClBvdWZQWUxXNlQyNHNZbUM4cnFkRFlJbTZPN2VHV096M0s3NEJBV1NzMmtpOVc0SHlLSlVRaDdRdWt0eTE2bWIKY2pHallOQVZGL1dUOEJmeFRCV3RtaHJtOXQzTHZ0MD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - client auth
