#!/bin/bash

openssl genrsa -out dev.key 2048
openssl req -new -key dev.key -subj "/CN=dev" -out dev.csr

cat dev.csr | base64 | tr -d '\n' > dev.csr.base64

kubectl apply -f dev.csr.yml
kubectl get csr
kubectl certificate approve dev


# decoding base64 certifiicate generated by kubernetes 
kubectl get csr dev -o yaml 

base64 -d "decoding base64 certifiicate generated by kubernetes into dev.csr" > dev.csr


kubectl --server https://192.168.56.110:6443 \
> --certificate-authority /etc/kubernetes/pki/ca.crt \
> --client-certificate dev.crt \
> --client-key dev.key \
> get pod 

