galaxy_info:
  author: Mohammad Mahdu Farnia
  description: Software Engineer
  company: Self-employed
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - kubeadm
    - k8s
    - kubelet
    - kubectl

dependencies: []
